import dotenv from 'dotenv';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcrypt';

import { logger } from '~/utils';
import { status } from '~/constants';
import { LoginSessionSchema } from '~/schemas/LoginSession';

dotenv.config();
export const refreshSession = async (req, res) => {
  //Codes that we might return coming from status
  const { OK, SERVER_ERROR, FORBIDDEN, PRE_CONDITION_FAILED } = status;

  //Destructuring refresh_token from the headers
  const { refresh_token } = req.headers;

  try {
    //Extracting the payload(data) from the token
    const { payload: payLoad } = jwt.decode(refresh_token, {
      complete: true,
    });

    //Making sure token is not expired
    if (new Date(payLoad.exp * 1000) < new Date(Date.now())) {
      return res.json({
        success: false,
        error: {
          code: PRE_CONDITION_FAILED,
          message: 'Token Expired',
        },
      });
    }

    //Checking token is generated by us
    const inDataBase = await LoginSessionSchema.findOne(
      { refresh_token },
      { _id: 1, remember_me: 1, user_id: 1, email: 1 },
    );

    if (!inDataBase || !inDataBase._id) {
      return res.json({
        success: false,
        error: {
          code: FORBIDDEN,
          message: 'Invalid Token',
        },
      });
    }

    //Generating hash for the tokens secret
    const hash = await bcrypt.hash(
      process.env.JWT_SECRET,
      parseInt(process.env.SALT_ROUNDS, 10),
    );

    //Generating the access token
    const access_token = jwt.sign(
      {
        user: {
          user_id: inDataBase.user_id,
          email: inDataBase.email,
        },
      },
      hash,
      {
        expiresIn: '7d',
      },
    );

    //Generating the refresh token
    const new_refresh_token = jwt.sign(
      {
        user: {
          user_id: inDataBase.user_id,
        },
      },
      hash,
      {
        expiresIn: '7d',
      },
    );

    //Generating the expiration date for tokens
    const expirationDate = new Date(
      new Date().setDate(new Date().getDate() + 7),
    );

    //Attaching the timestamps with the tokens
    const access_token_expiration_timestamp = expirationDate.getTime();
    const refresh_token_expiration_timestamp =
      access_token_expiration_timestamp;

    //Setting default or otherwise user sent value to remember_me
    await LoginSessionSchema.updateOne(
      { _id: inDataBase._id },
      {
        $set: {
          access_token_expiration_timestamp,
          refresh_token_expiration_timestamp,
          access_token,
          refresh_token: new_refresh_token,
        },
      },
    );

    //Sending response in case everything went well!
    return res.json({
      success: true,
      data: {
        code: OK,
        access_token_expiration_timestamp,
        refresh_token_expiration_timestamp,
        access_token,
        refresh_token,
        remember_me: inDataBase.remember_me,
      },
    });
  } catch (e) {
    //Log in case of any abnormal crash
    logger('error', 'Error:', e.message);
    return res.json({
      success: false,
      error: {
        code: SERVER_ERROR,
        message: 'Internal Server Error',
      },
    });
  }
};
